services:
  payara:
    build: .
    ports:
      - "4848:4848"
    environment:
      - DEPLOY_DIR=/opt/payara/appserver/glassfish/domains/domain1/autodeploy
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - payara
    networks:
      - app_network

networks:
  app_network: